### ISSUE TITLE
Error when doing a GraphQL request: "Cannot change rejection reason"

### ISSUE THREAD

**Issue by ahocquard** [overblog/dataloader-php#24]
Hello,

When I try to execute a request in **production** environment, I'm experiencing this issue:

```
{"code":500,"message":"Internal Server Error"}<br />
<b>Fatal error</b>:  Uncaught Exception: Cannot change rejection reason in /my/local/directory/poc/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php:63
Stack trace:
#0 /my/local/directory/poc/vendor/overblog/dataloader-php/src/DataLoader.php(418): GraphQL\Executor\Promise\Adapter\SyncPromise-&gt;reject(Object(RuntimeException))
#1 /my/local/directory/poc/vendor/overblog/dataloader-php/src/DataLoader.php(367): Overblog\DataLoader\DataLoader-&gt;failedDispatch(Array, Object(RuntimeException))
#2 /my/local/directory/poc/vendor/overblog/dataloader-php/src/DataLoader.php(349): Overblog\DataLoader\DataLoader-&gt;dispatchQueueBatch(Array)
#3 /my/local/directory/poc/vendor/overblog/dataloader-php/src/DataLoader.php(225): Overblog\DataLoader\DataLoader-&gt;dispatchQueue()
#4 /my/local/directory/poc/vendor/overblog/dataloader-php/src/DataLoader.php(297): Overblog\DataLoader\DataLoader-&gt;process()
#5 /my/local/directory/poc/vendor/over in <b>/my/local/directory/poc/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php</b> on line <b>63</b><br />
```

Something happens in the `destruct` function, but I have no idea why.
Is it configured wrongly ? 

When I debug, the message passed into the exception `GraphQL\Error\Error` is `DataLoader destroyed before promise complete.`.

Everything works fine without the loader.
My end to end tests are green with the dataloader (and it's disturbing...).

My graphql configuration is:
```
overblog_dataloader:
    defaults:
        promise_adapter: "overblog_dataloader.webonyx_graphql_sync_promise_adapter"
        options:
            batch: true
            cache: true
            max_batch_size: 100
            cache_map: "overblog_dataloader.cache_map"

    loaders:
        users:
            alias: "attribute_dataloader"
            batch_load_fn: "@pim_research.infrastructure.persistence.database.cached_attribute_repository:withCodes"
```

My type declaration:
```
    pim_research.infrastructure.delivery.api.graphql.type.family_type:
        class: '%pim_research.infrastructure.delivery.api.graphql.type.family_type.class%'
        arguments:
            - '@pim_research.infrastructure.delivery.api.graphql.types'
            - '@pim_research.infrastructure.persistence.database.cached_attribute_repository'
            - '@attribute_dataloader'
        tags:
            - { name: 'pim_research.infrastructure.delivery.api.graphql.type' }
        lazy: true
```

and my class:

```
class FamilyType extends ObjectType
{
    public function __construct(Types $types, AttributeRepository $attributeRepository, DataLoader $attributeDataLoader)
    {
        $config = [
            'name' => 'family',
            'description' => 'Family',
            'fields' => function() use ($types) {
                return [
                    'code' => Type::string(),
                    'attributes' => Type::listOf($types->get(AttributeType::class))
                ];
            },
            'resolveField' => function(Family $family, $args, $context, ResolveInfo $info) use ($attributeRepository, $attributeDataLoader) {
                switch ($info->fieldName) {
                    case 'code':
                        return $family->code()->getValue();
                    case 'attributes':
                        return $attributeDataLoader->loadMany($family->attributeCodes());
                        //return $attributeRepository->withCodes($family->attributeCodes());
                    default:
                        return null;
                }
            }
        ];
        parent::__construct($config);
    }
}
```

My dependency versions:
```
"webonyx/graphql-php": "v0.11.2"
"overblog/dataloader-php": "v0.5.2"
"overblog/dataloader-bundle": "v0.4.0"
```

Thanks.
